/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as MapRouteImport } from './routes/map'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModpacksIndexRouteImport } from './routes/modpacks.index'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as ModpacksSlugRouteImport } from './routes/modpacks.$slug'
import { Route as GuideSlugRouteImport } from './routes/guide/$slug'

const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksIndexRoute = ModpacksIndexRouteImport.update({
  id: '/modpacks/',
  path: '/modpacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksSlugRoute = ModpacksSlugRouteImport.update({
  id: '/modpacks/$slug',
  path: '/modpacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/guide/$slug',
  path: '/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/map': typeof MapRoute
  '/mods': typeof ModsRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/modpacks/$slug': typeof ModpacksSlugRoute
  '/guide': typeof GuideIndexRoute
  '/modpacks': typeof ModpacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/map': typeof MapRoute
  '/mods': typeof ModsRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/modpacks/$slug': typeof ModpacksSlugRoute
  '/guide': typeof GuideIndexRoute
  '/modpacks': typeof ModpacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/map': typeof MapRoute
  '/mods': typeof ModsRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/modpacks/$slug': typeof ModpacksSlugRoute
  '/guide/': typeof GuideIndexRoute
  '/modpacks/': typeof ModpacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/map'
    | '/mods'
    | '/guide/$slug'
    | '/modpacks/$slug'
    | '/guide'
    | '/modpacks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/map'
    | '/mods'
    | '/guide/$slug'
    | '/modpacks/$slug'
    | '/guide'
    | '/modpacks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/faq'
    | '/map'
    | '/mods'
    | '/guide/$slug'
    | '/modpacks/$slug'
    | '/guide/'
    | '/modpacks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  MapRoute: typeof MapRoute
  ModsRoute: typeof ModsRoute
  GuideSlugRoute: typeof GuideSlugRoute
  ModpacksSlugRoute: typeof ModpacksSlugRoute
  GuideIndexRoute: typeof GuideIndexRoute
  ModpacksIndexRoute: typeof ModpacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks/': {
      id: '/modpacks/'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof ModpacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks/$slug': {
      id: '/modpacks/$slug'
      path: '/modpacks/$slug'
      fullPath: '/modpacks/$slug'
      preLoaderRoute: typeof ModpacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/guide/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  MapRoute: MapRoute,
  ModsRoute: ModsRoute,
  GuideSlugRoute: GuideSlugRoute,
  ModpacksSlugRoute: ModpacksSlugRoute,
  GuideIndexRoute: GuideIndexRoute,
  ModpacksIndexRoute: ModpacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
